#!/usr/bin/env tsx

/**
 * Setup script for Microsoft Entra ID authentication
 * This script helps configure the environment variables needed for authentication
 */

import { writeFileSync, existsSync } from "fs";
import { createInterface } from "readline";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query: string): Promise<string> {
  return new Promise((resolve) => rl.question(query, resolve));
}

async function main(): Promise<void> {
  console.log("🔐 Microsoft Entra ID Authentication Setup");
  console.log("==========================================\n");

  console.log("Please provide your Azure App Registration details:\n");

  const clientId = await question("Enter your Client ID (Application ID): ");
  const tenantId = await question("Enter your Tenant ID (Directory ID): ");
  const redirectUri =
    (await question("Enter your Redirect URI (default: http://localhost:5173): ")) || "http://localhost:5173";

  if (!clientId || !tenantId) {
    console.error("❌ Client ID and Tenant ID are required!");
    process.exit(1);
  }

  const envContent = `# Azure AD Configuration
# Generated by setup script on ${new Date().toISOString()}

# Your Azure App Registration Client ID
VITE_AZURE_CLIENT_ID=${clientId}

# Your Azure Tenant Authority URL (for single tenant)
VITE_AZURE_AUTHORITY=https://login.microsoftonline.com/${tenantId}

# Redirect URI
VITE_AZURE_REDIRECT_URI=${redirectUri}
`;

  const envPath = join(__dirname, ".env.local");

  if (existsSync(envPath)) {
    const overwrite = await question("⚠️  .env.local file already exists. Overwrite? (y/N): ");
    if (overwrite.toLowerCase() !== "y") {
      console.log("Setup cancelled.");
      process.exit(0);
    }
  }

  writeFileSync(envPath, envContent);

  console.log("\n✅ Configuration saved to .env.local file!");
  console.log("\nNext steps:");
  console.log("1. Make sure your Azure App Registration is configured correctly");
  console.log("2. Run: npm run dev");
  console.log("3. Navigate to http://localhost:5173");
  console.log("\nFor detailed setup instructions, see AUTHENTICATION.md");

  rl.close();
}

main().catch((error: Error) => {
  console.error("Error:", error);
  process.exit(1);
});
