name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - main
      - feature/sql-server-bicep
    paths:
      - infra/**
      - .github/workflows/infra.yml

jobs:
  deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          lfs: false
          submodules: false
          clean: true

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep template
        run: |
          az deployment sub create \
            --name dep-${{ secrets.PROJECT_NAME }}-dev \
            --location swedencentral \
            --template-file ./infra/main.bicep \
            --parameters environment=Dev \
                        projectName=${{ secrets.PROJECT_NAME }} \
                        sqlAdminLogin=${{ secrets.SQL_ADMIN_LOGIN }} \
                        sqlAdminObjectId=${{ secrets.SQL_ADMIN_OBJECTID }}
